# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5eca51ae36b0cd7b17e0e03dacec38a61bcb55902a4eb4dbea70759942e4653d6106ef6b984f12eaa8f4a86aace752a630914cede61f77b7013cc9e993cf58b4

test:
  secret_key_base: 78ff0272d412d2011e02e8e47199d7f5aa0a52c7e1834861b3d5b120ef1f712c4ccca4bffaadc0b06c38f94b3cad9d8810a02986c34777c12d2beb4df01a3b40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
